config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  get 'profile/:id' => 'users#show', as: :user
  get 'login' => 'sessions#new', as: :login
  get 'signup' => 'users#new', as: :signup
  post 'login' => 'sessions#create'
  post 'signup' => 'users#create'
  delete 'logout' => 'sessions#destroy', as: :logout
  get 'admin_panel' => 'users#all', as: :admin_panel
  delete 'destroy_user' => 'users#destroy', as: :destroy_user
  get 'profile/:id/update' => 'users#edit' , as: :edit
  patch 'profile/:id' => 'users#update', as: :update
  get 'semesters/:id/new' => 'semesters#new', as: :new_semester
  post 'semesters/:id/new' => 'semesters#create', as: :save_semester
  delete "semesters/:id/delete/:number" => 'semesters#destroy', as: :delete_semester
end

app/models/infopage.rb
class Infopage < ActiveRecord::Base
	belongs_to :user
end

app/models/semester.rb
class Semester < ActiveRecord::Base
	belongs_to :user
	validates :number, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :semesters
	validates :email, :first_name, :last_name, presence: true

	def admin?
		self.role == 'admin'
	end
	
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

  helper_method :current_user, :current_user_session, :resource_user


  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

	def require_user 
  	redirect_to login_path unless current_user 
	end

  def require_no_user
    redirect_to root_path if current_user
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end

    def resource_user
    @resource_user ||=
      if current_user.admin?
        if params[:id].nil?
          current_user
        else
          User.find(params[:id])
        end
      else
        User.find(session[:user_id])
      end
  end

end

app/controllers/infopage_controller.rb
class InfopageController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController

	def new
	end

	def create
		if resource_semester.save
			resource_user.semesters.push resource_semester
			redirect_to user_path
		else
			render :new
		end
	end

	def destroy
		Semester.find_by(user_id: params[:id], number: params[:number]).destroy
		redirect_to user_path
	end

	private

	def resource_semester
		@resource_semester ||= Semester.new(semester_params)
	end

	def semester_params
		params.require(:semester).permit(:number, :toi, :discrete_math, :linal, :matlog, :ptms, :differential_equations)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	before_action :require_user, only: :destroy
	before_action :require_no_user, only: [:new, :create]

	def new
	end

	def create
	  @user = User.find_by_email(params[:session][:email])
	  if @user && @user.authenticate(params[:session][:password])
	    session[:user_id] = @user.id
	    if current_user.admin?
	    	redirect_to admin_panel_path
	    else
	    	redirect_to root_path
	  	end
	  else
	    render :new
  	end 
	end

	def destroy
		session[:user_id] = nil 
		redirect_to login_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	helper_method :users_collection, :semesters_collection

	before_action :require_user, only: [:show, :all]
	before_action :require_admin, only: [:all, :create, :new, :destroy, :edit, :update]

	def show
		redirect_to admin_panel_path if resource_user.admin?
	end

	def new
	end

	def all			
	end

	def create 
		@user = User.new(user_params)
		if @user.valid? && password_confirmed? && unique_user?
			@user.save
			redirect_to admin_panel_path
		else 
			render :new
			end 
	end

	def destroy
		resource_user.destroy
		redirect_to admin_panel_path
	end

	def edit
	end

	def update
		if resource_user.update(user_params)
			redirect_to(edit_path, :notice => "Пользователь изменен")
		else 
			redirect_to(edit_path, :notice => "Что-то пошло не так")
		end
	end

	def save#wtf #upd1. sam hz, ya dumal, ty napisal
		resource_user.save
		redirect_to root_path
	end

	private

	def semesters_collection
		@semesters_collection ||= resource_user.semesters
	end

	def users_collection
		@users_collection ||= User.all
	end

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password)
	end

	def unique_user? 	
		!User.exists?(email: params[:user][:email])
	end

	def password_confirmed?
		params[:user][:password] == params[:user][:password_confirmation]
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infopage_helper.rb
module InfopageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jetproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/semesters/new.html.erb
<div class="semester wrapper">
	<%= form_for :semester, url: new_semester_path do |f| %>
		<%= f.error_messages %></br>
		<%= f.text_field :number, :placeholder => "Номер семестра" ,class:"semester__edit-field"%> <!-- сделать обязательным для заполнения, иначе ломается -->
		<%= f.text_field :matlog, :placeholder => "Матлог",class:"semester__edit-field" %>
		<%= f.text_field :discrete_math, :placeholder => "Дискретка",class:"semester__edit-field" %>
		<%= f.text_field :toi, :placeholder => "ТОИ" ,class:"semester__edit-field"%>
		<%= f.text_field :linal, :placeholder => "Линал",class:"semester__edit-field" %>
		<%= f.text_field :ptms, :placeholder => "Теорвер",class:"semester__edit-field" %>
		<%= f.text_field :differential_equations, :placeholder => "Диффуры",class:"semester__edit-field" %>
		<%= f.submit "Добавить семестр",class:"button_redirect" %>
		<%= link_to "Вернуться к просмотру студента", :back , class:"button_redirect" %>
		<%= link_to "Вернуться в админ-панель", admin_panel_path ,class:"button_redirect" %>
	<% end %>
</div>

app/views/users/all.html.erb
<div class="admin-panel wrapper">
	<span class="admin-panel__title">Панель администратора</span>
	<%= link_to 'Выйти', logout_path, method: 'delete', class:"button_redirect" %>
	<%= link_to 'Зарегистрировать студента', signup_path , class:"button_redirect" %>
	<% users_collection.map do |user| %>
	<% unless user.admin? %>
		<div class="admin-panel__user">
			<p class="admin-panel__user-field">Имя: <%= user.first_name %></p>
			<p class="admin-panel__user-field">Фамилия: <%= user.last_name %></p>
			<p class="admin-panel__user-field">E-mail: <%= user.email %></p>
			<%= link_to 'Подробнее', user_path(user.id), class:"button_redirect" %>
		</div>
		<% end %>
	<% end %>
</div>

app/views/users/edit.html.erb
<div class="wrapper user">
	<%= form_for (resource_user) do |f| %>
		<%= f.text_field :first_name , placeholder: "Имя" , class:"user__edit-field" %>
		<%= f.text_field :last_name , placeholder: "Фамилия" , class:"user__edit-field" %>
		<%= f.email_field :email  , placeholder: "Email", class:"user__edit-field"  %>	
		<%= f.submit "Сохранить", method: "patch", class:"button_redirect" %>
		<%= link_to "Вернуться к просмотру студента", user_path ,class:"button_redirect" %>
		<%= link_to "Вернуться в админ-панель", admin_panel_path ,class:"button_redirect" %>
	<% end %>
	<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="login-form wrapper">
  <span class="login-form__title signup_title">Зарегистрируйте студента</span>
  <%= form_for :user, url: signup_path do |f| %>
    <%= f.error_messages :header_message => nil, :message => nil, :header_tag => :h3 %>
    <%= f.text_field :first_name, :placeholder => "Имя" , class:"login-form__text" %>
    <%= f.text_field :last_name, :placeholder => "Фамилия", class:"login-form__text" %>
    <%= f.text_field :email, :placeholder => "E-mail",class:"login-form__text" %>
    <%= f.password_field :password, :placeholder => "Пароль",class:"login-form__text" %>
    <%= f.password_field :password_confirmation, :placeholder => "Повторите пароль", class:"login-form__text" %>
    <%= f.submit "Зарегистрировать", class:"login-form__submit signup__submit" %>
    <%= link_to "Назад", admin_panel_path ,class:"login-form__submit signup__submit" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user wrapper">
	<span class="user__title">Профиль студента</span>
	<div class="user__info clearfix">
		<span class="user__info-field">Имя:</span>
		<span class="user__info-field"><%= resource_user.first_name %></span>
		<span class="user__info-field">Фамилия:</span>
		<span class="user__info-field"><%= resource_user.last_name %></span>
		<span class="user__info-field">E-mail:</span>
		<span class="user__info-field"><%= resource_user.email %></span> 
	</div>

	<% semesters_collection.map do |s| %>
	<table class="semester__table">
		<th class="semester__table_th" colspan="2"><%= s.number %> семестр</th>
		<tr class="semester__table_tr">
			<td class="semester__table_td">Матлог</td>
			<td class="semester__table_td"><%= s.matlog %></td>
		</tr>
		<tr class="semester__table_tr">
			<td class="semester__table_td">Теорвер</td>
			<td class="semester__table_td"><%= s.ptms %></td>
		</tr>
		<tr class="semester__table_tr">
			<td class="semester__table_td">Диффуры</td>
			<td class="semester__table_td"><%= s.differential_equations %></td>
		</tr>
		<tr class="semester__table_tr">
			<td class="semester__table_td">ТОИ</td>
			<td class="semester__table_td"><%= s.toi %></td>
		</tr>
		<tr class="semester__table_tr">
			<td class="semester__table_td">Дискретка</td>
			<td class="semester__table_td"><%= s.discrete_math %></td>
		</tr>
		<tr class="semester__table_tr">
			<td class="semester__table_td">Линал</td>
			<td class="semester__table_td"><%= s.linal %></td>
		</tr>
		<% if current_user.admin? %>
		<tr>
			<td colspan="2" >
				<%= link_to 'Удалить семестр', delete_semester_path(number: s.number), method: 'delete' , data: { confirm: 'Вы уверены, что хотите удалить этот семестр?' } ,class:"button_delete" %>
			</td>
		</tr>
		<% end %>
	</table>
	<% end %>

	<% if current_user.admin? %>
		<%= link_to "Добавить семестр", new_semester_path, method: 'get', class:"button_redirect" %>
		<%= link_to "Изменить данные", edit_path(id: resource_user.id), method: 'get', class:"button_redirect" %>
		<%= link_to 'Удалить студента', destroy_user_path(id: resource_user.id), method: 'delete', data: { confirm: 'Вы уверены, что хотите удалить студента из базы?' }, class:"button_delete" %>
		<%= link_to "Вернуться в админ-панель", admin_panel_path ,class:"button_redirect" %>
	<% else %>
		<%= link_to 'Выйти', logout_path, method: 'delete' , class:"button_redirect" %>
	<% end %>
</div>